ColectaChatIndex:
    pattern:  /chat/
    defaults: { _controller: ColectaIntranetBundle:Chat:index }
ColectaChatPost:
    pattern:  /chat/post.{method}
    defaults: { _controller: ColectaIntranetBundle:Chat:post }
ColectaChatReload:
    pattern:  /chat/reload/{lastinput}
    defaults: { _controller: ColectaIntranetBundle:Chat:reload }
ColectaChatMore:
    pattern:  /chat/more/{until}
    defaults: { _controller: ColectaIntranetBundle:Chat:more }
ColectaActivitiesIndex:
    pattern:  /actividades/
    defaults: { _controller: ColectaIntranetBundle:Activities:index }
ColectaActivitiesYearPerformance:
    pattern:  /actividades/{year}
    defaults: { _controller: ColectaIntranetBundle:Activities:yearPerformance }
ColectaActivitiesRank:
    pattern:  /actividades/rank/
    defaults: { _controller: ColectaIntranetBundle:Activities:rank }
ColectaActivitiesRankSummary:
    pattern:  /actividades/rank/summary/
    defaults: { _controller: ColectaIntranetBundle:Activities:rankSummary }
ColectaActivitiesYearRank:
    pattern:  /actividades/rank/{year}
    defaults: { _controller: ColectaIntranetBundle:Activities:yearPointsRank }
ColectaActivitiesYearTuryRank:
    pattern:  /actividades/turyrank/{year}
    defaults: { _controller: ColectaIntranetBundle:Activities:yearTuryRank }
ColectaPaymentIndex:
    pattern:  /pagos/
    defaults: { _controller: ColectaIntranetBundle:Payment:index }
ColectaLotteryIndex:
    pattern:  /loteria/
    defaults: { _controller: ColectaIntranetBundle:Lottery:index }
ColectaVehicleIndex:
    pattern:  /vehiculos/
    defaults: { _controller: ColectaIntranetBundle:Vehicle:index }
ColectaMovementIndex:
    pattern:  /contabilidad/
    defaults: { _controller: ColectaIntranetBundle:Movement:index }
ColectaMovementAdd:
    pattern:  /contabilidad/add/
    defaults: { _controller: ColectaIntranetBundle:Movement:add }
