ColectaChatIndex:
    pattern:  /chat/
    defaults: { _controller: ColectaIntranetBundle:Chat:index }
ColectaChatPost:
    pattern:  /chat/post/
    defaults: { _controller: ColectaIntranetBundle:Chat:post }
ColectaChatReload:
    pattern:  /chat/reload/{lastinput}
    defaults: { _controller: ColectaIntranetBundle:Chat:reload }
ColectaActivitiesIndex:
    pattern:  /actividades/
    defaults: { _controller: ColectaIntranetBundle:Activities:index }
ColectaActivitiesRank:
    pattern:  /actividades/rank/
    defaults: { _controller: ColectaIntranetBundle:Activities:rank }
ColectaPaymentIndex:
    pattern:  /pagos/
    defaults: { _controller: ColectaIntranetBundle:Payment:index }
ColectaLotteryIndex:
    pattern:  /loteria/
    defaults: { _controller: ColectaIntranetBundle:Lottery:index }
ColectaVehicleIndex:
    pattern:  /vehiculos/
    defaults: { _controller: ColectaIntranetBundle:Vehicle:index }
ColectaMovementIndex:
    pattern:  /contabilidad/
    defaults: { _controller: ColectaIntranetBundle:Movement:index }
ColectaMovementAdd:
    pattern:  /contabilidad/add/
    defaults: { _controller: ColectaIntranetBundle:Movement:add }
