parameters:
#    colecta_backend.example.class: Colecta\BackendBundle\Example

services:
#    colecta_backend.example:
#        class: %colecta_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
