ColectaFolderIndex:
    pattern:  /carpeta/
    defaults: { _controller: ColectaFilesBundle:Folder:index }
ColectaFolderCreate:
    pattern:  /carpeta/crear/
    defaults: { _controller: ColectaFilesBundle:Folder:create }
ColectaFolderView:
    pattern:  /carpeta/{slug}
    defaults: { _controller: ColectaFilesBundle:Folder:view }
ColectaFolderEdit:
    pattern:  /carpeta/{slug}/edit/
    defaults: { _controller: ColectaFilesBundle:Folder:edit }
ColectaFolderDelete:
    pattern:  /carpeta/{slug}/eliminar/
    defaults: { _controller: ColectaFilesBundle:Folder:delete }
ColectaFileIndex:
    pattern:  /archivo/
    defaults: { _controller: ColectaFilesBundle:File:index }
ColectaFilePage:
    pattern:  /archivo/pagina/{page}
    defaults: { _controller: ColectaFilesBundle:File:page }
ColectaFileCreate:
    pattern:  /archivo/crear/
    defaults: { _controller: ColectaFilesBundle:File:new }
ColectaFileNew:
    pattern:  /archivo/nuevo/
    defaults: { _controller: ColectaFilesBundle:Folder:new }
ColectaFilePick:
    pattern:  /archivo/crear/{slug}/
    defaults: { _controller: ColectaFilesBundle:File:pick }
ColectaFileXHRUpload:
    pattern:  /archivo/XHR/upload/
    defaults: { _controller: ColectaFilesBundle:File:XHRUpload }
ColectaFileXHRPreview:
    pattern:  /archivo/XHR/preview/{token}
    defaults: { _controller: ColectaFilesBundle:File:XHRPreview }
ColectaFileXHRProcess:
    pattern:  /archivo/crear/{slug}/process/
    defaults: { _controller: ColectaFilesBundle:File:XHRProcess }
ColectaFileUpload:
    pattern:  /fileupload/
    defaults: { _controller: ColectaFilesBundle:File:upload }
ColectaFileView:
    pattern:  /archivo/{slug}
    defaults: { _controller: ColectaFilesBundle:File:view }
ColectaFileEdit:
    pattern:  /archivo/{slug}/edit/
    defaults: { _controller: ColectaFilesBundle:File:edit }
ColectaFileDelete:
    pattern:  /archivo/{slug}/delete/
    defaults: { _controller: ColectaFilesBundle:File:delete }
ColectaFileDownload:
    pattern:  /archivo/descargar/{slug}.{type}
    defaults: { _controller: ColectaFilesBundle:File:download }
ColectaFileThumbnail:
    pattern:  /archivo/thumbnail/{width}/{height}/{slug}/
    defaults: { _controller: ColectaFilesBundle:File:thumbnail }
ColectaFileResize:
    pattern:  /archivo/resize/{width}/{height}/{slug}/
    defaults: { _controller: ColectaFilesBundle:File:resize }