ColectaFolderIndex:
    pattern:  /folder/
    defaults: { _controller: ColectaFilesBundle:Folder:index }
ColectaFolderView:
    pattern:  /folder/{slug}
    defaults: { _controller: ColectaFilesBundle:Folder:view }
ColectaFolderEdit:
    pattern:  /folder/{slug}/edit
    defaults: { _controller: ColectaFilesBundle:Folder:edit }
ColectaFileIndex:
    pattern:  /file/
    defaults: { _controller: ColectaFilesBundle:File:index }
ColectaFilePage:
    pattern:  /file/page/{page}
    defaults: { _controller: ColectaFilesBundle:File:page }
ColectaFileNew:
    pattern:  /file/new/
    defaults: { _controller: ColectaFilesBundle:File:new }
ColectaFileUpload:
    pattern:  /fileupload/
    defaults: { _controller: ColectaFilesBundle:File:upload }
ColectaFileView:
    pattern:  /file/{slug}
    defaults: { _controller: ColectaFilesBundle:File:view }
ColectaFileEdit:
    pattern:  /file/{slug}/edit/
    defaults: { _controller: ColectaFilesBundle:File:view }
