ColectaFolderIndex:
    pattern:  /carpeta/
    defaults: { _controller: ColectaFilesBundle:Folder:index }
ColectaFolderView:
    pattern:  /carpeta/{slug}
    defaults: { _controller: ColectaFilesBundle:Folder:view }
ColectaFolderEdit:
    pattern:  /carpeta/{slug}/edit/
    defaults: { _controller: ColectaFilesBundle:Folder:edit }
ColectaFileIndex:
    pattern:  /archivo/
    defaults: { _controller: ColectaFilesBundle:File:index }
ColectaFilePage:
    pattern:  /archivo/pagina/{page}
    defaults: { _controller: ColectaFilesBundle:File:page }
ColectaFileNew:
    pattern:  /archivo/crear/
    defaults: { _controller: ColectaFilesBundle:File:new }
ColectaFileUpload:
    pattern:  /fileupload/
    defaults: { _controller: ColectaFilesBundle:File:upload }
ColectaFileView:
    pattern:  /archivo/{slug}
    defaults: { _controller: ColectaFilesBundle:File:view }
ColectaFileEdit:
    pattern:  /archivo/{slug}/edit/
    defaults: { _controller: ColectaFilesBundle:File:edit }
ColectaFileDelete:
    pattern:  /archivo/{slug}/delete/
    defaults: { _controller: ColectaFilesBundle:File:delete }
ColectaFileDownload:
    pattern:  /archivo/descargar/{slug}.{type}
    defaults: { _controller: ColectaFilesBundle:File:download }
ColectaFileThumbnail:
    pattern:  /archivo/thumbnail/{slug}/{width}/{height}/
    defaults: { _controller: ColectaFilesBundle:File:thumbnail }
ColectaFileResize:
    pattern:  /archivo/resize/{slug}/{width}/{height}/
    defaults: { _controller: ColectaFilesBundle:File:resize }