ColectaFolderView:
    pattern:  /folder/{slug}
    defaults: { _controller: ColectaFilesBundle:Folder:view }
ColectaFileView:
    pattern:  /file/{slug}
    defaults: { _controller: ColectaFilesBundle:File:view }
