colecta_site:
    resource: "@ColectaSiteBundle/Resources/config/routing.yml"
    prefix:   /

colecta_backend:
    resource: "@ColectaBackendBundle/Resources/config/routing.yml"
    prefix:   /

stats:
    resource: "@StatsBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
ColectaIntranetBundle:
    resource: "@ColectaIntranetBundle/Resources/config/routing.yml"
    prefix:   /intranet/

ColectaActivityBundle:
    resource: "@ColectaActivityBundle/Resources/config/routing.yml"
    prefix:   /

ColectaColectiveBundle:
    resource: "@ColectaColectiveBundle/Resources/config/routing.yml"
    prefix:   /

ColectaFilesBundle:
    resource: "@ColectaFilesBundle/Resources/config/routing.yml"
    prefix:   /

ColectaItemBundle:
    resource: "@ColectaItemBundle/Resources/config/routing.yml"
    prefix:   /

ColectaUserBundle:
    resource: "@ColectaUserBundle/Resources/config/routing.yml"
    prefix:   /

