jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
        frontend:
            pattern:  ^/
            anonymous: ~
            form_login:
                login_path: userLogin
                check_path: userLoginCheck
            logout:
                path: userLogout
            remember_me:
                key:        hjb87adi4hbi24dhbsa5d
                lifetime:   2592000

    access_control:
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    
    providers:
        users:
            entity: { class: Colecta\UserBundle\Entity\User, property: mail }

    encoders:
        Colecta\UserBundle\Entity\User: plaintext