security:

    firewalls:
        frontend:
            pattern:  ^/
            anonymous: ~
            form_login:
                login_path: userLogin
                check_path: userLoginCheck

    access_control:
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    
    
    providers:
        users:
            entity: { class: Colecta\UserBundle\Entity\User, property: mail }

    encoders:
        Colecta\UserBundle\Entity\User: plaintext