parameters:
    welcomeText: "Hola %N!\n\nYa puedes acceder a tu cuenta en ---web_title---\n\nSimplemente tienes que seguir el siguiente enlace:\n%L\n"
twig:
    globals:
        web_title: 'Título de la web'
        web_description: 'Descripción para buscadores'
        web_theme: theme-blue
        theme_sidebar: left
        allowed_tags: '<br><img>#<span><a><ol><ul><li>'
        rich_text_editor: 0
        summary_max_length: 1200
        web_logo: ''
        web_header_img: {  }
        itemIcons:
            Item/Post: comments
            Activity/Event: calendar
            Activity/Route: compass
            Activity/Place: map-marker
            Files/File: folder-open
            Files/Folder: folder-open
        adsense: '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-0259798523659720" data-ad-slot="9859843508" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>'
