ColectaBackendIndex:
    pattern:  /back/
    defaults: { _controller: ColectaBackendBundle:Default:index }

ColectaBackendSettingsIndex:
    pattern:  /back/settings/
    defaults: { _controller: ColectaBackendBundle:Settings:index }

ColectaBackendUserIndex:
    pattern:  /back/user/
    defaults: { _controller: ColectaBackendBundle:User:index } 
ColectaBackendUserProfile:
    pattern:  /back/user/profile/{user_id}/
    defaults: { _controller: ColectaBackendBundle:User:profile }    
ColectaBackendNewUser:
    pattern:  /back/user/new/
    defaults: { _controller: ColectaBackendBundle:User:newUser }    
ColectaBackendUserActivityReport:
    pattern:  /back/user/report/activity/
    defaults: { _controller: ColectaBackendBundle:User:activityReport, format:html }
ColectaBackendUserActivityReportCSV:
    pattern:  /back/user/report/activity/csv/
    defaults: { _controller: ColectaBackendBundle:User:activityReport, format:csv }
ColectaBackendRolesIndex:
    pattern:  /back/roles/
    defaults: { _controller: ColectaBackendBundle:User:roles } 
ColectaBackendRoleCreate:
    pattern:  /back/roles/create/
    defaults: { _controller: ColectaBackendBundle:User:roleCreate } 
ColectaBackendRoleDelete:
    pattern:  /back/roles/{role_id}/delete/
    defaults: { _controller: ColectaBackendBundle:User:roleDelete } 
ColectaBackendRoleEdit:
    pattern:  /back/roles/{role_id}/
    defaults: { _controller: ColectaBackendBundle:User:roleEdit } 
    
ColectaBackendPointsIndex:
    pattern:  /back/points/
    defaults: { _controller: ColectaBackendBundle:Points:index } 
ColectaBackendPointsNewCase:
    pattern:  /back/points/new/
    defaults: { _controller: ColectaBackendBundle:Points:newCase } 
ColectaBackendPointsCase:
    pattern:  /back/points/{case_id}/
    defaults: { _controller: ColectaBackendBundle:Points:editCase } 
ColectaBackendPointsCaseDelete:
    pattern:  /back/points/{case_id}/delete/
    defaults: { _controller: ColectaBackendBundle:Points:deleteCase } 
    
ColectaBackendMemoIndex:
    pattern:  /back/memo/
    defaults: { _controller: ColectaBackendBundle:User:memo } 

ColectaBackendPageIndex:
    pattern:  /back/page/
    defaults: { _controller: ColectaBackendBundle:Page:index } 
ColectaBackendNewPage:
    pattern:  /back/page/new/
    defaults: { _controller: ColectaBackendBundle:Page:newPage } 
ColectaBackendPage:
    pattern:  /back/page/{page_id}
    defaults: { _controller: ColectaBackendBundle:Page:editPage } 
ColectaBackendPageDelete:
    pattern:  /back/page/{page_id}/delete/
    defaults: { _controller: ColectaBackendBundle:Page:deletePage } 
ColectaBackendPageMoveUp:
    pattern:  /back/page/{page_id}/up/
    defaults: { _controller: ColectaBackendBundle:Page:movePageUp } 
ColectaBackendPageMoveDown:
    pattern:  /back/page/{page_id}/down/
    defaults: { _controller: ColectaBackendBundle:Page:movePageDown } 
ColectaBackendNewLink:
    pattern:  /back/link/new/
    defaults: { _controller: ColectaBackendBundle:Settings:newLink } 
ColectaBackendLink:
    pattern:  /back/link/{link_id}
    defaults: { _controller: ColectaBackendBundle:Settings:editLink } 
ColectaBackendLinkDelete:
    pattern:  /back/link/{link_id}/delete/
    defaults: { _controller: ColectaBackendBundle:Settings:deleteLink } 
    
ColectaBackendLotteryIndex:
    pattern:  /back/lottery/
    defaults: { _controller: ColectaBackendBundle:Lottery:index }
ColectaBackendLotteryUser:
    pattern:  /back/lottery/user/{user_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:user }
ColectaBackendLotteryAddShred:
    pattern:  /back/lottery/addShred/
    defaults: { _controller: ColectaBackendBundle:Lottery:addShred }
ColectaBackendLotteryRemoveShred:
    pattern:  /back/lottery/removeShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:removeShred }
ColectaBackendLotteryReturnShred:
    pattern:  /back/lottery/returnShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:returnShred }
ColectaBackendLotteryPaidShred:
    pattern:  /back/lottery/paidShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:paidShred }
ColectaBackendLotteryUnpaidShred:
    pattern:  /back/lottery/unpaidShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:unpaidShred }
