ColectaBackendIndex:
    pattern:  /back/
    defaults: { _controller: ColectaBackendBundle:Default:index }

ColectaBackendSettingsIndex:
    pattern:  /back/settings/
    defaults: { _controller: ColectaBackendBundle:Settings:index }
    
ColectaBackendUserIndex:
    pattern:  /back/user/
    defaults: { _controller: ColectaBackendBundle:User:index }
    
ColectaBackendLotteryIndex:
    pattern:  /back/lottery/
    defaults: { _controller: ColectaBackendBundle:Lottery:index }
ColectaBackendLotteryUser:
    pattern:  /back/lottery/user/{user_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:user }
ColectaBackendLotteryAddShred:
    pattern:  /back/lottery/addShred/
    defaults: { _controller: ColectaBackendBundle:Lottery:addShred }
ColectaBackendLotteryRemoveShred:
    pattern:  /back/lottery/removeShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:removeShred }
ColectaBackendLotteryReturnShred:
    pattern:  /back/lottery/returnShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:returnShred }
ColectaBackendLotteryPaidShred:
    pattern:  /back/lottery/paidShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:paidShred }
ColectaBackendLotteryUnpaidShred:
    pattern:  /back/lottery/unpaidShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:unpaidShred }
