ColectaBackendIndex:
    pattern:  /back/
    defaults: { _controller: ColectaBackendBundle:Default:index }

ColectaBackendSettingsIndex:
    pattern:  /back/settings/
    defaults: { _controller: ColectaBackendBundle:Settings:index }

ColectaBackendUserIndex:
    pattern:  /back/user/
    defaults: { _controller: ColectaBackendBundle:User:index } 
ColectaBackendUserProfile:
    pattern:  /back/user/profile/{user_id}/
    defaults: { _controller: ColectaBackendBundle:User:profile }    
ColectaBackendNewUser:
    pattern:  /back/user/new/
    defaults: { _controller: ColectaBackendBundle:User:newUser }    
ColectaBackendUserActivityReport:
    pattern:  /back/user/report/activity/
    defaults: { _controller: ColectaBackendBundle:User:activityReport, format:html }
ColectaBackendUserActivityReportCSV:
    pattern:  /back/user/report/activity/csv/
    defaults: { _controller: ColectaBackendBundle:User:activityReport, format:csv }
ColectaBackendRolesIndex:
    pattern:  /back/roles/
    defaults: { _controller: ColectaBackendBundle:User:roles } 
ColectaBackendRoleCreate:
    pattern:  /back/roles/create/
    defaults: { _controller: ColectaBackendBundle:User:roleCreate } 
ColectaBackendRoleDelete:
    pattern:  /back/roles/{role_id}/delete/
    defaults: { _controller: ColectaBackendBundle:User:roleDelete } 
ColectaBackendRoleEdit:
    pattern:  /back/roles/{role_id}/
    defaults: { _controller: ColectaBackendBundle:User:roleEdit } 
    
ColectaBackendLotteryIndex:
    pattern:  /back/lottery/
    defaults: { _controller: ColectaBackendBundle:Lottery:index }
ColectaBackendLotteryUser:
    pattern:  /back/lottery/user/{user_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:user }
ColectaBackendLotteryAddShred:
    pattern:  /back/lottery/addShred/
    defaults: { _controller: ColectaBackendBundle:Lottery:addShred }
ColectaBackendLotteryRemoveShred:
    pattern:  /back/lottery/removeShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:removeShred }
ColectaBackendLotteryReturnShred:
    pattern:  /back/lottery/returnShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:returnShred }
ColectaBackendLotteryPaidShred:
    pattern:  /back/lottery/paidShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:paidShred }
ColectaBackendLotteryUnpaidShred:
    pattern:  /back/lottery/unpaidShred/{shred_id}
    defaults: { _controller: ColectaBackendBundle:Lottery:unpaidShred }
