parameters:
    colecta.install.class: Colecta\BackendBundle\Services\InstallService
 
services:
    colecta.install:
        class: "%colecta.install.class%"
        arguments: [ @doctrine.orm.entity_manager ]