ColectaDashboard:
    pattern:  /
    defaults: { _controller: ColectaItemBundle:Default:dashboard }
ColectaDashboardPage:
    pattern:  /pagina/{page}/
    defaults: { _controller: ColectaItemBundle:Default:dashboardPage }
ColectaSearch:
    pattern:  /buscar/
    defaults: { _controller: ColectaItemBundle:Default:search }
ColectaSearchPage:
    pattern:  /buscar/{page}/
    defaults: { _controller: ColectaItemBundle:Default:searchPage }
ColectaAjaxSearch:
    pattern:  /ajaxsearch/
    defaults: { _controller: ColectaItemBundle:Default:ajaxsearch }
ColectaItemRelate:
    pattern:  /item/{id}/relate/
    defaults: { _controller: ColectaItemBundle:Default:relate }
ColectaComment:
    pattern:  /comment/{slug}/
    defaults: { _controller: ColectaItemBundle:Comment:comment }
ColectaPostIndex:
    pattern:  /foro/
    defaults: { _controller: ColectaItemBundle:Post:index }
ColectaPostPage:
    pattern:  /foro/pagina/{page}/
    defaults: { _controller: ColectaItemBundle:Post:page }
ColectaPostNew:
    pattern:  /foro/crear/
    defaults: { _controller: ColectaItemBundle:Post:new }
ColectaPostCreate:
    pattern:  /crear/publicacion/
    defaults: { _controller: ColectaItemBundle:Post:create }
ColectaPostView:
    pattern:  /foro/{slug}/
    defaults: { _controller: ColectaItemBundle:Post:view }
ColectaPostEdit:
    pattern:  /foro/{slug}/editar/
    defaults: { _controller: ColectaItemBundle:Post:edit }
ColectaCategoryPage:
    pattern:  /categoria/{slug}/pagina/{page}/
    defaults: { _controller: ColectaItemBundle:Category:page }
ColectaCategoryView:
    pattern:  /categoria/{slug}/
    defaults: { _controller: ColectaItemBundle:Category:view }
ColectaItemLike:
    pattern:  /like/{slug}/
    defaults: { _controller: ColectaItemBundle:Default:like }

