ColectaDashboard:
    pattern:  /
    defaults: { _controller: ColectaItemBundle:Default:dashboard }
ColectaDashboardPage:
    pattern:  /page/{page}
    defaults: { _controller: ColectaItemBundle:Default:dashboardPage }
ColectaSearch:
    pattern:  /search/
    defaults: { _controller: ColectaItemBundle:Default:search }
ColectaAjaxSearch:
    pattern:  /ajaxsearch/
    defaults: { _controller: ColectaItemBundle:Default:ajaxsearch }
ColectaItemRelate:
    pattern:  /item/{id}/relate
    defaults: { _controller: ColectaItemBundle:Default:relate }
ColectaComment:
    pattern:  /comment/{slug}
    defaults: { _controller: ColectaItemBundle:Comment:comment }
ColectaPostIndex:
    pattern:  /post/
    defaults: { _controller: ColectaItemBundle:Post:index }
ColectaPostPage:
    pattern:  /post/page/{page}
    defaults: { _controller: ColectaItemBundle:Post:page }
ColectaPostCreate:
    pattern:  /new/post/
    defaults: { _controller: ColectaItemBundle:Post:create }
ColectaPostView:
    pattern:  /post/{slug}
    defaults: { _controller: ColectaItemBundle:Post:view }
ColectaPostEdit:
    pattern:  /post/{slug}/edit
    defaults: { _controller: ColectaItemBundle:Post:edit }
ColectaCategoryPage:
    pattern:  /category/{slug}/page/{page}
    defaults: { _controller: ColectaItemBundle:Category:page }
ColectaCategoryView:
    pattern:  /category/{slug}
    defaults: { _controller: ColectaItemBundle:Category:view }

