ColectaDashboard:
    pattern:  /
    defaults: { _controller: ColectaItemBundle:Default:dashboard }
ColectaDashboardPage:
    pattern:  /pagina/{page}/
    defaults: { _controller: ColectaItemBundle:Default:dashboardPage }
ColectaSearch:
    pattern:  /buscar/
    defaults: { _controller: ColectaItemBundle:Default:search }
ColectaSearchPage:
    pattern:  /buscar/{page}/
    defaults: { _controller: ColectaItemBundle:Default:searchPage }
ColectaAjaxSearch:
    pattern:  /ajaxsearch/
    defaults: { _controller: ColectaItemBundle:Default:ajaxsearch }
ColectaItemRelate:
    pattern:  /item/{id}/relate/
    defaults: { _controller: ColectaItemBundle:Default:relate }
ColectaComment:
    pattern:  /comment/{slug}/
    defaults: { _controller: ColectaItemBundle:Comment:comment }
ColectaPostIndex:
    pattern:  /textos/
    defaults: { _controller: ColectaItemBundle:Post:index }
ColectaPostPage:
    pattern:  /textos/pagina/{page}/
    defaults: { _controller: ColectaItemBundle:Post:page }
ColectaPostNew:
    pattern:  /textos/crear/
    defaults: { _controller: ColectaItemBundle:Post:new }
ColectaPostCreate:
    pattern:  /crear/texto/
    defaults: { _controller: ColectaItemBundle:Post:create }
ColectaPostView:
    pattern:  /textos/{slug}/
    defaults: { _controller: ColectaItemBundle:Post:view }
ColectaPostEdit:
    pattern:  /textos/{slug}/editar/
    defaults: { _controller: ColectaItemBundle:Post:edit }
ColectaPostDelete:
    pattern:  /textos/{slug}/eliminar/
    defaults: { _controller: ColectaItemBundle:Post:delete }
ColectaCategoryPage:
    pattern:  /categoria/{slug}/pagina/{page}/
    defaults: { _controller: ColectaItemBundle:Category:page }
ColectaCategoryFormlist:
    pattern:  /categorias/formlist/
    defaults: { _controller: ColectaItemBundle:Category:formlist, selected : 0, simplified : 1 }
ColectaCategoryView:
    pattern:  /categoria/{slug}/
    defaults: { _controller: ColectaItemBundle:Category:view }
ColectaCategoryIndex:
    pattern:  /categoria/
    defaults: { _controller: ColectaItemBundle:Category:index }
ColectaItemLike:
    pattern:  /like/{slug}/
    defaults: { _controller: ColectaItemBundle:Default:like }
ColectaContact:
    pattern:  /contacto/
    defaults: { _controller: ColectaItemBundle:Default:contact }
ColectaSinceLastVisit:
    pattern:  /ultimavisita/
    defaults: { _controller: ColectaItemBundle:Default:sinceLastVisit }
ColectaSinceLastVisitDismiss:
    pattern:  /ultimavisita/dismiss/{date}
    defaults: { _controller: ColectaItemBundle:Default:dismissSinceLastVisit }


ColectaSinceLastVisitPage:
    pattern:  /ultimavisita/{page}/
    defaults: { _controller: ColectaItemBundle:Default:sinceLastVisitPage }