ColectaDashboard:
    pattern:  /
    defaults: { _controller: ColectaItemBundle:Default:dashboard }
ColectaPostView:
    pattern:  /post/{slug}
    defaults: { _controller: ColectaItemBundle:Post:view }
