ColectaDashboard:
    pattern:  /
    defaults: { _controller: ColectaItemBundle:Default:dashboard }
ColectaComment:
    pattern:  /comment/{slug}
    defaults: { _controller: ColectaItemBundle:Comment:comment }
ColectaPostIndex:
    pattern:  /post/
    defaults: { _controller: ColectaItemBundle:Post:index }
ColectaPostCreate:
    pattern:  /new/post/
    defaults: { _controller: ColectaItemBundle:Post:create }
ColectaPostView:
    pattern:  /post/{slug}
    defaults: { _controller: ColectaItemBundle:Post:view }
ColectaCategoryView:
    pattern:  /category/{slug}
    defaults: { _controller: ColectaItemBundle:Category:view }
