parameters:
#    colecta_item.example.class: Colecta\ItemBundle\Example

services:
    colecta.twig.item_extension:
        class: Colecta\ItemBundle\Twig\ItemExtension
        arguments: [@doctrine, @router]
        tags:
            - { name: twig.extension }
            
    kernel.listener.colecta_exception_lstener:
        class: Colecta\ItemBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }