parameters:
#    colecta_item.example.class: Colecta\ItemBundle\Example

services:
    colecta.twig.item_extension:
        class: Colecta\ItemBundle\Twig\ItemExtension
        arguments: [@doctrine, @router]
        tags:
            - { name: twig.extension }
            
    colecta.doctrine.searchitempostpersist:
        class: Colecta\ItemBundle\EventListener\SearchIndexer
        tags: 
            - { name: doctrine.event_listener, event: postPersist }
            
    colecta.doctrine.searchitempostupdate:
        class: Colecta\ItemBundle\EventListener\SearchIndexer
        tags: 
            - { name: doctrine.event_listener, event: postUpdate }
            
    colecta.doctrine.searchitempreremove:
        class: Colecta\ItemBundle\EventListener\SearchIndexer
        tags: 
            - { name: doctrine.event_listener, event: preRemove }