parameters:
#    colecta_item.example.class: Colecta\ItemBundle\Example

services:
#    colecta_item.example:
#        class: %colecta_item.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
