parameters:
#    colecta_item.example.class: Colecta\ItemBundle\Example

services:
    colecta.twig.item_extension:
        class: Colecta\ItemBundle\Twig\ItemExtension
        arguments: [@doctrine, @router]
        tags:
            - { name: twig.extension }