ColectaContact:
    pattern:  /contacto/
    defaults: { _controller: ColectaSiteBundle:Default:contact }
ColectaPagesNavigation:
    pattern:  /pagesnavigation/{context}/
    defaults: { _controller: ColectaSiteBundle:Page:navigation }
ColectaPage:
    pattern:  /pagina/{slug}/
    defaults: { _controller: ColectaSiteBundle:Page:view }