services:
    recordVisit:
        class: Colecta\StatsBundle\Service\Service
        arguments: [@request, @doctrine, @session]
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: recordVisit }