ColectaPollCreate:
    pattern:  /new/poll/
    defaults: { _controller: ColectaColectiveBundle:Poll:create }
ColectaPolleIndex:
    pattern:  /poll/
    defaults: { _controller: ColectaColectiveBundle:Poll:index }
ColectaPollView:
    pattern:  /poll/{slug}
    defaults: { _controller: ColectaColectiveBundle:Poll:view }
ColectaContestCreate:
    pattern:  /new/contest/
    defaults: { _controller: ColectaColectiveBundle:Contest:create }
ColectaContestIndex:
    pattern:  /contest/
    defaults: { _controller: ColectaColectiveBundle:Contest:index }
ColectaContestView:
    pattern:  /contest/{slug}
    defaults: { _controller: ColectaColectiveBundle:Contest:view }
