ColectaPollCreate:
    pattern:  /new/poll/
    defaults: { _controller: ColectaColectiveBundle:Poll:create }
ColectaPollIndex:
    pattern:  /poll/
    defaults: { _controller: ColectaColectiveBundle:Poll:index }
ColectaPollPage:
    pattern:  /poll/page/{page}
    defaults: { _controller: ColectaColectiveBundle:Poll:page }
ColectaPollView:
    pattern:  /poll/{slug}
    defaults: { _controller: ColectaColectiveBundle:Poll:view }
ColectaPollVote:
    pattern:  /vote/{slug}/
    defaults: { _controller: ColectaColectiveBundle:Poll:vote }
ColectaContestCreate:
    pattern:  /new/contest/
    defaults: { _controller: ColectaColectiveBundle:Contest:create }
ColectaContestIndex:
    pattern:  /contest/
    defaults: { _controller: ColectaColectiveBundle:Contest:index }
ColectaContestPage:
    pattern:  /contest/page/{page}
    defaults: { _controller: ColectaColectiveBundle:Contest:page }
ColectaContestView:
    pattern:  /contest/{slug}
    defaults: { _controller: ColectaColectiveBundle:Contest:view }
