userLogin:
    pattern:  /login
    defaults: { _controller: ColectaUserBundle:Default:login }
    
userLoginCheck:
    pattern:  /login_check
    
userLogout:
    pattern:  /logout
    
userProfile:
    pattern:  /user/{id}
    defaults: { _controller: ColectaUserBundle:User:profile }

userNotifications:
    pattern:  /notifications/
    defaults: { _controller: ColectaUserBundle:Notification:index }
    
userNotificationDismiss:
    pattern:  /notification/dismiss/{id}
    defaults: { _controller: ColectaUserBundle:Notification:dismiss }