userLogin:
    pattern:  /login
    defaults: { _controller: ColectaUserBundle:Default:login }
    
userLoginCheck:
    pattern:  /login_check
    
userLogout:
    pattern:  /logout
    
userResetPassword:
    pattern:  /resetpassword/
    defaults: { _controller: ColectaUserBundle:Default:resetPassword }
    
userResetPasswordCode:
    pattern:  /resetpassword/{uid}/{code}/
    defaults: { _controller: ColectaUserBundle:Default:newPassword }
    
userProfile:
    pattern:  /usuario/{id}
    defaults: { _controller: ColectaUserBundle:User:profile }
    
userAvatar:
    pattern:  /avatar/{uid}/{width}/{height}/
    defaults: { _controller: ColectaUserBundle:User:avatar }
    
userEditProfile:
    pattern:  /editprofile/
    defaults: { _controller: ColectaUserBundle:User:editProfile }

userNotifications:
    pattern:  /notificaciones/
    defaults: { _controller: ColectaUserBundle:Notification:index }
    
userNotificationDismiss:
    pattern:  /notificaciones/dismiss/{id}
    defaults: { _controller: ColectaUserBundle:Notification:dismiss }
    
ColectaAjaxUserSearch:
    pattern:  /ajaxusersearch/
    defaults: { _controller: ColectaUserBundle:User:ajaxsearch }