userLogin:
    pattern:  /login
    defaults: { _controller: ColectaUserBundle:Default:login }
    
userLoginCheck:
    pattern:  /login_check
    
userLogout:
    pattern:  /logout
    
userResetPassword:
    pattern:  /reset-password
    defaults: { _controller: ColectaUserBundle:Default:resetPassword }
    
userProfile:
    pattern:  /user/{id}
    defaults: { _controller: ColectaUserBundle:User:profile }
    
userEditProfile:
    pattern:  /editprofile/
    defaults: { _controller: ColectaUserBundle:User:editProfile }

userNotifications:
    pattern:  /notifications/
    defaults: { _controller: ColectaUserBundle:Notification:index }
    
userNotificationDismiss:
    pattern:  /notification/dismiss/{id}
    defaults: { _controller: ColectaUserBundle:Notification:dismiss }
    
ColectaAjaxUserSearch:
    pattern:  /ajaxusersearch/
    defaults: { _controller: ColectaUserBundle:User:ajaxsearch }