userLogin:
    pattern:  /login
    defaults: { _controller: ColectaUserBundle:Default:login }
    
userLoginCheck:
    pattern:  /login_check
    
userLogout:
    pattern:  /logout
    
userResetPassword:
    pattern:  /resetpassword/
    defaults: { _controller: ColectaUserBundle:Default:resetPassword }
    
userResetPasswordCode:
    pattern:  /resetpassword/{uid}/{code}/
    defaults: { _controller: ColectaUserBundle:Default:newPassword }
    
userProfile:
    pattern:  /usuario/{id}
    defaults: { _controller: ColectaUserBundle:User:profile }
    
ColectaUserAssistances:
    pattern:  /usuario/{id}/asistencias/
    defaults: { _controller: ColectaUserBundle:User:assistances }
    
userAvatar:
    pattern:  /avatar/{uid}/{width}/{height}/
    defaults: { _controller: ColectaUserBundle:User:avatar }
    
userEditProfile:
    pattern:  /editprofile/
    defaults: { _controller: ColectaUserBundle:User:editProfile }

userNotifications:
    pattern:  /notificaciones/
    defaults: { _controller: ColectaUserBundle:Notification:index }
    
userNotificationDismissAll:
    pattern:  /notificaciones/dismiss/all/
    defaults: { _controller: ColectaUserBundle:Notification:dismissAll }
    
userNotificationDismiss:
    pattern:  /notificaciones/dismiss/{id}
    defaults: { _controller: ColectaUserBundle:Notification:dismiss }

userNotificationsLoad:
    pattern:  /notificaciones/{page}
    defaults: { _controller: ColectaUserBundle:Notification:load }

userMessages:
    pattern:  /mensajes/
    defaults: { _controller: ColectaUserBundle:Message:index }
    
userSentMessages:
    pattern:  /mensajes/enviados/
    defaults: { _controller: ColectaUserBundle:Message:sent }

userMessageNew:
    pattern:  /mensajes/nuevo/
    defaults: { _controller: ColectaUserBundle:Message:new }
    
userMessageResponse:
    pattern:  /mensajes/responder/{responseto}
    defaults: { _controller: ColectaUserBundle:Message:response }
    
ColectaAjaxUserSearch:
    pattern:  /ajaxusersearch/
    defaults: { _controller: ColectaUserBundle:User:ajaxsearch }