parameters:
#    colecta_user.example.class: Colecta\UserBundle\Example

services:
#    colecta_user.example:
#        class: %colecta_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
