services:
    colectauser:
        class: Colecta\UserBundle\Service\Service
        arguments: [@security.context, @doctrine]
        
    twig.extension.colectauser:
        class: Colecta\UserBundle\Service\ServiceExtension
        arguments: [@colectauser]
        tags:
            - { name: twig.extension }