ColectaPlaceCreate:
    pattern:  /crear/lugar/
    defaults: { _controller: ColectaActivityBundle:Place:create }
ColectaPlaceIndex:
    pattern:  /lugares/
    defaults: { _controller: ColectaActivityBundle:Place:index }
ColectaPlaceNew:
    pattern:  /lugares/crear/
    defaults: { _controller: ColectaActivityBundle:Place:new }
ColectaPlacePage:
    pattern:  /lugares/pagina/{page}
    defaults: { _controller: ColectaActivityBundle:Place:page }
ColectaPlaceView:
    pattern:  /lugares/{slug}
    defaults: { _controller: ColectaActivityBundle:Place:view }
ColectaPlaceEdit:
    pattern:  /lugares/{slug}/editar/
    defaults: { _controller: ColectaActivityBundle:Place:edit }
ColectaEventCreate:
    pattern:  /crear/actividad/
    defaults: { _controller: ColectaActivityBundle:Event:create }
ColectaEventIndex:
    pattern:  /actividades/
    defaults: { _controller: ColectaActivityBundle:Event:index }
ColectaEventNew:
    pattern:  /actividades/crear/
    defaults: { _controller: ColectaActivityBundle:Event:new }
ColectaEventPage:
    pattern:  /actividades/pagina/{page}
    defaults: { _controller: ColectaActivityBundle:Event:page }
ColectaEventDate:
    pattern:  /actividades/fecha/{date}
    defaults: { _controller: ColectaActivityBundle:Event:date }
ColectaEventView:
    pattern:  /actividades/{slug}
    defaults: { _controller: ColectaActivityBundle:Event:view }
ColectaEventEdit:
    pattern:  /actividades/{slug}/editar/
    defaults: { _controller: ColectaActivityBundle:Event:edit }
ColectaEventAsist:
    pattern:  /actividades/{slug}/asist/
    defaults: { _controller: ColectaActivityBundle:Event:assistance }
ColectaEventUnasist:
    pattern:  /actividades/{slug}/unasist/
    defaults: { _controller: ColectaActivityBundle:Event:unassistance }
ColectaEventUpdateAsist:
    pattern:  /actividades/{slug}/updateasist/
    defaults: { _controller: ColectaActivityBundle:Event:updateAssistances }
ColectaRouteUpload:
    pattern:  /upload/rutas/
    defaults: { _controller: ColectaActivityBundle:Route:upload }
ColectaRouteCreate:
    pattern:  /crear/ruta/
    defaults: { _controller: ColectaActivityBundle:Route:create }
ColectaRouteNew:
    pattern:  /rutas/crear/
    defaults: { _controller: ColectaActivityBundle:Route:new }
ColectaRouteIndex:
    pattern:  /rutas/
    defaults: { _controller: ColectaActivityBundle:Route:index }
ColectaRoutePage:
    pattern:  /rutas/pagina/{page}
    defaults: { _controller: ColectaActivityBundle:Route:page }
ColectaRouteDownload:
    pattern:  /rutas/descargar/{slug}.{extension}
    defaults: { _controller: ColectaActivityBundle:Route:download }
ColectaRouteView:
    pattern:  /rutas/{slug}
    defaults: { _controller: ColectaActivityBundle:Route:view }
ColectaRouteEdit:
    pattern:  /rutas/{slug}/editar/
    defaults: { _controller: ColectaActivityBundle:Route:edit }
ColectaRouteMap:
    pattern:  /routemap/{id}
    defaults: { _controller: ColectaActivityBundle:Route:map }
