ColectaMapIndex:
    pattern:  /mapas/
    defaults: { _controller: ColectaActivityBundle:Default:index }
ColectaMapPage:
    pattern:  /mapas/pagina/{page}
    defaults: { _controller: ColectaActivityBundle:Default:page }

ColectaPlaceCreate:
    pattern:  /crear/lugar/
    defaults: { _controller: ColectaActivityBundle:Place:create }
ColectaPlaceIndex:
    pattern:  /lugares/
    defaults: { _controller: ColectaActivityBundle:Place:index }
ColectaPlaceNew:
    pattern:  /lugares/crear/
    defaults: { _controller: ColectaActivityBundle:Place:new }
ColectaPlacePage:
    pattern:  /lugares/pagina/{page}
    defaults: { _controller: ColectaActivityBundle:Place:page }
ColectaPlaceView:
    pattern:  /lugares/{slug}
    defaults: { _controller: ColectaActivityBundle:Place:view }
ColectaPlaceEdit:
    pattern:  /lugares/{slug}/editar/
    defaults: { _controller: ColectaActivityBundle:Place:edit }
ColectaPlaceDelete:
    pattern:  /lugares/{slug}/eliminar/
    defaults: { _controller: ColectaActivityBundle:Place:delete }

ColectaEventCreate:
    pattern:  /crear/actividad/
    defaults: { _controller: ColectaActivityBundle:Event:create }
ColectaEventIndex:
    pattern:  /actividades/
    defaults: { _controller: ColectaActivityBundle:Event:index }
ColectaEventCategoryIndex:
    pattern:  /actividades/categoria/{slug}/
    defaults: { _controller: ColectaActivityBundle:Event:category }
ColectaEventCategoryPage:
    pattern:  /actividades/categoria/{slug}/{page}
    defaults: { _controller: ColectaActivityBundle:Event:categoryPage }
ColectaEventICS:
    pattern:  /calendar.ics
    defaults: { _controller: ColectaActivityBundle:Event:ics }
ColectaEventNew:
    pattern:  /actividades/crear/
    defaults: { _controller: ColectaActivityBundle:Event:new }
ColectaEventDetails:
    pattern:  /actividades/crear/detalles/
    defaults: { _controller: ColectaActivityBundle:Event:detailsForm }
ColectaEventPage:
    pattern:  /actividades/pagina/{page}
    defaults: { _controller: ColectaActivityBundle:Event:page }
ColectaEventDate:
    pattern:  /actividades/fecha/{date}
    defaults: { _controller: ColectaActivityBundle:Event:date }
ColectaEventView:
    pattern:  /actividades/{slug}
    defaults: { _controller: ColectaActivityBundle:Event:view }
ColectaEventEdit:
    pattern:  /actividades/{slug}/editar/
    defaults: { _controller: ColectaActivityBundle:Event:edit }
ColectaEventDelete:
    pattern:  /actividades/{slug}/eliminar/
    defaults: { _controller: ColectaActivityBundle:Event:delete }
ColectaEventAsist:
    pattern:  /actividades/{slug}/asist/
    defaults: { _controller: ColectaActivityBundle:Event:assistance }
ColectaEventUnasist:
    pattern:  /actividades/{slug}/unasist/
    defaults: { _controller: ColectaActivityBundle:Event:unassistance }
ColectaEventUpdateAsist:
    pattern:  /actividades/{slug}/updateasist/
    defaults: { _controller: ColectaActivityBundle:Event:updateAssistances }
ColectaEventAssistanceConfirm:
    pattern:  /actividades/{slug}/confirm/{user_id}
    defaults: { _controller: ColectaActivityBundle:Event:assistanceConfirm }
ColectaEventAssistanceRemove:
    pattern:  /actividades/{slug}/remove/{user_id}
    defaults: { _controller: ColectaActivityBundle:Event:assistanceRemove }
ColectaEventAssistanceUpdate:
    pattern:  /actividades/{slug}/update/{user_id}
    defaults: { _controller: ColectaActivityBundle:Event:assistanceUpdate }
ColectaEventAboutics:
    pattern:  /icsinfo.html
    defaults: { _controller: ColectaActivityBundle:Event:aboutics }

ColectaRouteUpload:
    pattern:  /upload/rutas/
    defaults: { _controller: ColectaActivityBundle:Route:upload }
ColectaRouteCreate:
    pattern:  /crear/ruta/
    defaults: { _controller: ColectaActivityBundle:Route:create }
ColectaRouteNew:
    pattern:  /rutas/crear/
    defaults: { _controller: ColectaActivityBundle:Route:new }
ColectaRouteXHRUpload:
    pattern:  /rutas/XHR/upload/
    defaults: { _controller: ColectaActivityBundle:Route:XHRUpload }
ColectaRouteXHRPreview:
    pattern:  /rutas/XHR/preview/{token}
    defaults: { _controller: ColectaActivityBundle:Route:XHRPreview }
ColectaRouteIndex:
    pattern:  /rutas/
    defaults: { _controller: ColectaActivityBundle:Route:index }
ColectaRoutePage:
    pattern:  /rutas/pagina/{page}
    defaults: { _controller: ColectaActivityBundle:Route:page }
ColectaRouteCategoryIndex:
    pattern:  /rutas/categoria/{slug}/
    defaults: { _controller: ColectaActivityBundle:Route:category }
ColectaRouteCategoryPage:
    pattern:  /rutas/categoria/{slug}/{page}
    defaults: { _controller: ColectaActivityBundle:Route:categoryPage }
ColectaRouteDownload:
    pattern:  /rutas/descargar/{slug}.{extension}
    defaults: { _controller: ColectaActivityBundle:Route:download }
ColectaRouteView:
    pattern:  /rutas/{slug}
    defaults: { _controller: ColectaActivityBundle:Route:view }
ColectaRouteEdit:
    pattern:  /rutas/{slug}/editar/
    defaults: { _controller: ColectaActivityBundle:Route:edit }
ColectaRouteDelete:
    pattern:  /rutas/{slug}/eliminar/
    defaults: { _controller: ColectaActivityBundle:Route:delete }
ColectaRouteMap:
    pattern:  /routemap/{id}
    defaults: { _controller: ColectaActivityBundle:Route:map }
ColectaRouteProfile:
    pattern:  /routeprofile/{id}
    defaults: { _controller: ColectaActivityBundle:Route:profile }
