ColectaPlaceCreate:
    pattern:  /new/place/
    defaults: { _controller: ColectaActivityBundle:Place:create }
ColectaPlaceIndex:
    pattern:  /place/
    defaults: { _controller: ColectaActivityBundle:Place:index }
ColectaPlacePage:
    pattern:  /place/page/{page}
    defaults: { _controller: ColectaActivityBundle:Place:page }
ColectaPlaceView:
    pattern:  /place/{slug}
    defaults: { _controller: ColectaActivityBundle:Place:view }
ColectaPlaceEdit:
    pattern:  /place/{slug}/edit/
    defaults: { _controller: ColectaActivityBundle:Place:edit }
ColectaEventCreate:
    pattern:  /new/event/
    defaults: { _controller: ColectaActivityBundle:Event:create }
ColectaEventIndex:
    pattern:  /event/
    defaults: { _controller: ColectaActivityBundle:Event:index }
ColectaEventPage:
    pattern:  /event/page/{page}
    defaults: { _controller: ColectaActivityBundle:Event:page }
ColectaEventView:
    pattern:  /event/{slug}
    defaults: { _controller: ColectaActivityBundle:Event:view }
ColectaEventEdit:
    pattern:  /event/{slug}/edit/
    defaults: { _controller: ColectaActivityBundle:Event:edit }
ColectaEventAsist:
    pattern:  /event/{slug}/asist/
    defaults: { _controller: ColectaActivityBundle:Event:assistance }
ColectaRouteUpload:
    pattern:  /upload/route/
    defaults: { _controller: ColectaActivityBundle:Route:upload }
ColectaRouteCreate:
    pattern:  /new/route/
    defaults: { _controller: ColectaActivityBundle:Route:create }
ColectaRouteIndex:
    pattern:  /route/
    defaults: { _controller: ColectaActivityBundle:Route:index }
ColectaRoutePage:
    pattern:  /route/page/{page}
    defaults: { _controller: ColectaActivityBundle:Route:page }
ColectaRouteView:
    pattern:  /route/{slug}
    defaults: { _controller: ColectaActivityBundle:Route:view }
ColectaRouteEdit:
    pattern:  /route/{slug}/edit/
    defaults: { _controller: ColectaActivityBundle:Route:edit }
ColectaRouteMap:
    pattern:  /routemap/{id}
    defaults: { _controller: ColectaActivityBundle:Route:map }
