ColectaPlaceCreate:
    pattern:  /new/place/
    defaults: { _controller: ColectaActivityBundle:Place:create }
ColectaPlaceIndex:
    pattern:  /place/
    defaults: { _controller: ColectaActivityBundle:Place:index }
ColectaPlaceView:
    pattern:  /place/{slug}
    defaults: { _controller: ColectaActivityBundle:Place:view }
ColectaEventCreate:
    pattern:  /new/event/
    defaults: { _controller: ColectaActivityBundle:Event:create }
ColectaEventIndex:
    pattern:  /event/
    defaults: { _controller: ColectaActivityBundle:Event:index }
ColectaEventView:
    pattern:  /event/{slug}
    defaults: { _controller: ColectaActivityBundle:Event:view }
ColectaRouteUpload:
    pattern:  /upload/route/
    defaults: { _controller: ColectaActivityBundle:Route:upload }
ColectaRouteCreate:
    pattern:  /new/route/
    defaults: { _controller: ColectaActivityBundle:Route:create }
ColectaRouuteIndex:
    pattern:  /route/
    defaults: { _controller: ColectaActivityBundle:Route:index }
ColectaRouteView:
    pattern:  /route/{slug}
    defaults: { _controller: ColectaActivityBundle:Route:view }
