ColectaPlaceView:
    pattern:  /place/{slug}
    defaults: { _controller: ColectaActivityBundle:Place:view }

ColectaEventView:
    pattern:  /event/{slug}
    defaults: { _controller: ColectaActivityBundle:Event:view }
